language: rust
rust:
  - stable
  - beta
  - nightly

env:
  global:
    - secure: l8hKyZzEGNBE/j44xOFJS04MRM1icLvBMT5QK6sujJ+wN9X/jE4pBDLuL3ByajnQyspJOgqvNvYkMchQGKW7Aqan+VorKGk/CFf7+ly3Dpeitq/tNTZdu454kKGvMWfU7a2ETVHg19uN5Lo9p40tWiTTYJ+0lt8tK+AEkAriLbs=

script:
  - cargo build
  - cargo test
  - cargo doc

after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

cache: cargo
matrix:
  fast_finish: true
  include:
    - rust: nightly-2018-05-06
      env: # use env so updating versions causes cache invalidation
        - CLIPPY_VERSION=0.0.197
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION
      script:
        - cargo fmt -- --write-mode=check
        - cargo clippy
